nelmio_api_doc:
    documentation:
        info:
            title: Saloodo Technical Challenge for Backend Software Engineer
            description: REST API interfaces to manage products and orders
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/api$) # Accepts routes under /api except /api/doc
