#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: ../src/Controller/
    type: rest

app.swagger_ui:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
